server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbtest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: test-provider1
mybatis:
  type-aliases-package: com.leyou.testprovider1.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 10 #\u670D\u52A1\u7EED\u7EA6\u5FC3\u8DF3(renew)\u7684\u95F4\u9694\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2
    lease-expiration-duration-in-seconds: 10 #\u670D\u52A1\u5931\u6548\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u503C90\u79D2
logging: #\u9ED8\u8BA4\u4F7F\u7528LogBack\u65E5\u5FD7\u7CFB\u7EDF,slf4j\u65E5\u5FD7 \u3002\u5BF9\u4E8Efeign\u7EC4\u4EF6\u7684\u65E5\u5FD7\u6709\u4E0D\u540C\uFF0C\u8BF7\u770B\u5177\u4F53\u7B14\u8BB0
  level:
    com.leyou.testprovider1: debug #\u8981\u5199\u4E0A\u5305\u540D\u624D\u53EF\u4EE5
  #file: yo-test.log #\u9ED8\u8BA4\u540D\u79F0\uFF1Aspring.log
  path: /home/test-provider1 #\u9ED8\u8BA4\u662F\u9879\u76EE\u7684\u6839\u76EE\u5F55\u4E0B\uFF0C  \u548C\u4E0A\u4E00\u4E2Afile\u53C2\u6570\u8FD9\u4E24\u4E2A\u914D\u7F6E\u4E0D\u80FD\u540C\u65F6\u751F\u6548
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'